### ISSUE TITLE
Crashes attempting to run IABs MRAID compliance test ad

### ISSUE THREAD

**Issue by joshuaostrom** [PubMatic/pubmatic-sdk-ios#1]
The SDK appears to fail when running IABs expandable compliance test markup:

http://mraid.iab.net/compliance/units/twopart-expand-part1.txt

Wanted to reach out before taking the time to dev / submit a patch here.

**Comment by pm-pramod-jadhav** [comment]
Thank you for reaching out, we are working on this issue. We will release fix in coming release.

**Comment by jadhavp** [comment]
Fixed in release [v5.2.1](https://github.com/PubMatic/pubmatic-sdk-ios/releases/tag/5.2.1)

**Comment by pm-pramod-jadhav** [comment]
Fixed in release [5.2.1](https://github.com/PubMatic/pubmatic-sdk-ios/releases/tag/5.2.1)
